services:
  postgres:
    image: postgres:16-alpine
    container_name: cronos_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-cronos}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cronos_redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: cronos_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: "hydra"

volumes:
  postgres_data:
